[features]
seeds = false
skip-lint = false
[programs.localnet]
goal_post = "CjGeFgjXCinepzwnpP9UphxiQ2D6XGgxKDYZh34dYina"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/fury/ubuntu-deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
